apiVersion: apps/v1
kind: deployment
metadata:
    name: client-deployment
spec:
    replicas: 3
    selector:
        matchLabels:
            component: web
    template:
        metadate:
            labels:
                component: web
        spec:
            containers:
                - name: client
                  image: taylorzhangyx/multi-client